config/routes.rb
SampleApp::Application.routes.draw do
  get "people/new"

  resources :courses do
    get :autocomplete_course_title, :on => :collection
  end
  
  resources :people do
    get :autocomplete_person_lastname, :on => :collection
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :courses #, only: [:show, :create, :destroy, :autocomplete_course_title]
  resources :reviews, only: [:destroy]
  resources :votes, only: [:new, :create]
  resources :people
        
  root to: 'static_pages#home'

  match '/facebooks/create', to: 'facebooks#create'
  match '/facebooks/oauth', to: 'facebooks#oauth' , :as => :oauth_facebooks
  match '/users/:activation_token/activate', to: 'users#activate' , :as => :activate_user
  match '/create_review', to: 'inputs#create', via: :post
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/landing_page', to: 'static_pages#landing_page'
  match '/auth/google_oauth2/callback', to:'users#google_oauth2' # dev env
  match '/oauth2callback', to:'users#google_oauth2' # production env
  

end

app/views/shared/_course_form.html.erb
<%= form_for setup_course(@course) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
	  <%= f.text_field :title %>
	  
	  <%= f.fields_for :schedules do |ff| %>

	    <%= ff.select :semester, [['Spring', 1], ['Summer', 2], ['Fall', 3], ['Winter', 4]] ,
	    selected: ['Fall', 3] %>
	    <%= ff.label 'year' %>:
	    <%= ff.select :year, [2011,2012,2013,2014] %>
	  <% end %>
	  
	  <br/> 
	 
	  <% (1..4).each do |index| %>
        <% f.fields_for :verse do |ff| %>
	      <%= ff.text_area :content, placeholder: "Compose new micropost #{index}..." %>
	      <%= hidden_field_tag 'topic_id', index %>
        <% end %>
      <% end %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_current_user_info.html.erb
<% if signed_in? %>
	<a href="<%= user_path(current_user) %>">
	  <%= gravatar_for current_user %>
	</a>
	<h1><%= link_to display_name(current_user), current_user %></h1>
	<span><%= pluralize(current_user.reviews.count, "review") %></span>
	<span><%= pluralize(current_user.verses.count, "like") %></span>
<% else %>
	<%= gravatar_for current_user %>
	<h1>Guest</h1>
	<%= link_to 'Sign up', signup_path %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_input_form.html.erb
<div class="field" style="background-color:#eeeefd;padding: 5px;-moz-border-radius: 5px;
border-radius: 5px;">
  <%= form_tag('/create_review', :method => "POST", id: 'review_form') do%>
    <span style="color: darkblue; font-weight:bold;display:inline-block;margin: 8px 0 0 0";> My Review </span>
  <span  style="color: darkblue; display:inline-block; float:right">
  <%= field_set_tag nil, class: 'rating' do %>
    <%= radio_button_tag(:rating, 5) %>
    <%= label_tag 'rating_5', '5', title: 'Rocks!' %>
    <%= radio_button_tag(:rating, 4) %>
    <%= label_tag 'rating_4', '4', title: 'Pretty good' %>
    <%= radio_button_tag(:rating, 3) %>
    <%= label_tag 'rating_3', '3', title: 'Meh' %>
    <%= radio_button_tag(:rating, 2) %>
    <%= label_tag 'rating_2', '2', title: 'Kinda bad' %>
    <%= radio_button_tag(:rating, 1) %>
    <%= label_tag 'rating_1','1', title: 'Waste of time' %>
    <span id='radio_error'></span>
  <% end %>
  </span>
	<%= autocomplete_field_tag :title, nil, autocomplete_course_title_courses_path, size: 50,  placeholder: "Course Title", class: 'required' %>
	<%= select_tag(:semester, 
	    options_for_select([['Spring', 1], ['Summer', 2], ['Fall', 3], ['Winter', 4]],3)) %>
	<%= select_tag :year, 
	  options_for_select([['2011', 2011], ['2012', 2012], ['2013', 2013]],2012), class: "year" %>
	<%= autocomplete_field_tag :professor, nil, autocomplete_person_lastname_people_path, size: 50,  placeholder: "Prof's Lastname", class: 'required' %>
  <%= text_area_tag :content_1, nil, spellcheck: true, minlength: 3, maxlength: 300, placeholder: verse_topic(1), title: verse_topic(1) %>

	<%= text_area_tag :content_2, nil, spellcheck: true, minlength: 3, maxlength: 300, placeholder: verse_topic(2), title: verse_topic(2) %>
	<%= text_area_tag :content_3, nil, spellcheck: true, minlength: 3, maxlength: 300, placeholder: verse_topic(3), title: verse_topic(3) %>
	<%= text_area_tag :content_4, nil, spellcheck: true, minlength: 3, maxlength: 300, placeholder: verse_topic(4), title: verse_topic(4) %>
  <br>
    <%= submit_tag "Submit Review", class: "btn btn-primary", disabled: !signed_in?, title: signed_in? ? nil : 'Please sign in to submit.' %>
    <%if !signed_in?%><br/><small class='timestamp'>Please sign in to submit.</small><%end%>
  <% end %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<% if facebook_link(@user).blank? %>
  <%= gravatar_for @user %>
<% else %>
  <a href="<%= facebook_link(@user) %>">
    <%= gravatar_for @user %>
  </a>
<% end %>
<h1><%= display_name(@user) %></h1>
<span><%= pluralize(@user.reviews.count, "review") %></span>
<span><%= pluralize(@user.received_likes, "like") %></span>