config/routes.rb
SampleApp::Application.routes.draw do
  get "people/new"

  resources :courses do
    get :autocomplete_course_title, :on => :collection
  end
  
  resources :people do
    get :autocomplete_person_lastname, :on => :collection
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :courses #, only: [:show, :create, :destroy, :autocomplete_course_title]
  resources :reviews, only: [:destroy]
  resources :votes, only: [:new, :create]
  resources :people
        
  root to: 'static_pages#home'

  match '/facebooks/create', to: 'facebooks#create'
  match '/facebooks/oauth', to: 'facebooks#oauth' , :as => :oauth_facebooks
  match '/users/:activation_token/activate', to: 'users#activate' , :as => :activate_user
  match '/create_review', to: 'inputs#create', via: :post
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/landing_page', to: 'static_pages#landing_page'
  match '/auth/google_oauth2/callback', to:'users#google_oauth2' # dev env
  match '/oauth2callback', to:'users#google_oauth2' # production env
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    2013 courseverse.com all rights reserved
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  <!--%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %-->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CourseVerse", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li>
                 <%= link_to 'Connect to Facebook', oauth_facebooks_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
         <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>